name: Add reviewers Example Job
on:
  pull_request:
    types: [opened, reopened]

env:
  # Change variable to add reviewers with comma separator.
  # Example: `sakhnovict,user1,user2`.
  REVIEWERS: 'petati'

jobs:
  onOpenedPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          reviewers: 'petati'
          token: ${{ secrets.GITHUB_TOKEN }}
